# Generated by Django 2.2.7 on 2019-11-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
